import type { AuditRecord } from "./types";

export const MOCK_AUDITS: AuditRecord[] = [
  {
    id: "1",
    manager_name: "Менеджер Айнур",
    interaction_type: "call",
    duration_seconds: 124,
    ai_score: 30,
    ai_summary: "Слив лида. Менеджер не попыталась закрыть сделку и не отработала возражение 'Дорого'.",
    checklist: [
      { name: "Приветствие", passed: true, comment: "" },
      { name: "Выявление потребности", passed: true, comment: "" },
      { name: "Отработка возражений", passed: false, comment: "Проигнорировала сомнения клиента" },
      { name: "Закрытие на визит", passed: false, comment: "Сама положила трубку" },
    ],
    transcript: [
      { speaker: "manager", text: "Алло, клиника." },
      { speaker: "client", text: "Здравствуйте, сколько стоят брекеты?" },
      { speaker: "manager", text: "От 500 тысяч." },
      { speaker: "client", text: "Ого, дороговато, я подумаю." },
      { speaker: "manager", text: "Хорошо, до свидания.", is_mistake: true, ai_comment: "КРИТИЧЕСКАЯ ОШИБКА: Нужно было предложить рассрочку или бесплатную консультацию." },
    ],
  },
  {
    id: "2",
    manager_name: "AI-Агент (WhatsApp)",
    interaction_type: "whatsapp",
    duration_seconds: 0,
    ai_score: 100,
    ai_summary: "Идеальная конверсия. Выявлена потребность, предложена рассрочка, клиент записан на завтра.",
    checklist: [
      { name: "Приветствие", passed: true, comment: "" },
      { name: "Выявление потребности", passed: true, comment: "" },
      { name: "Отработка возражений", passed: true, comment: "" },
      { name: "Закрытие на визит", passed: true, comment: "" },
    ],
    transcript: [
      { speaker: "client", text: "Хочу записаться" },
      { speaker: "manager", text: "Здравствуйте! С удовольствием подберу для вас время. Вас интересует лечение или эстетика (виниры/брекеты)?" },
    ],
  },
  {
    id: "3",
    manager_name: "Менеджер Дамир",
    interaction_type: "call",
    duration_seconds: 247,
    ai_score: 42,
    ai_summary: "Потерянный клиент. Менеджер не представился, назвал цену без контекста, не предложил альтернативу.",
    checklist: [
      { name: "Приветствие", passed: false, comment: "Не представился по имени, не назвал клиента" },
      { name: "Выявление потребности", passed: false, comment: "Не задал ни одного уточняющего вопроса" },
      { name: "Отработка возражений", passed: false, comment: "Попытка была, но неубедительная" },
      { name: "Закрытие на визит", passed: true, comment: "" },
    ],
    transcript: [
      { speaker: "manager", text: "SmileDent, слушаю.", is_mistake: true, ai_comment: "Не представился, не назвал имя клиента. Нарушение стандарта приветствия." },
      { speaker: "client", text: "Здравствуйте, интересуюсь чисткой зубов." },
      { speaker: "manager", text: "Чистка стоит 15 000." },
      { speaker: "client", text: "А что входит?" },
      { speaker: "manager", text: "Ультразвук и полировка. Записать?", is_mistake: true, ai_comment: "Не раскрыл ценность услуги: не упомянул Air Flow, осмотр, консультацию. Ответ слишком сухой." },
      { speaker: "client", text: "Я ещё подумаю, спасибо." },
      { speaker: "manager", text: "Хорошо, звоните." },
    ],
  },
  {
    id: "4",
    manager_name: "Менеджер Алия",
    interaction_type: "call",
    duration_seconds: 312,
    ai_score: 92,
    ai_summary: "Отличный звонок. Менеджер провела диалог по скрипту, выявила потребности и записала на визит. Небольшая пауза при ответе на вопрос о гарантии.",
    checklist: [
      { name: "Приветствие", passed: true, comment: "" },
      { name: "Выявление потребности", passed: true, comment: "" },
      { name: "Отработка возражений", passed: true, comment: "" },
      { name: "Закрытие на визит", passed: true, comment: "" },
    ],
    transcript: [
      { speaker: "manager", text: "Здравствуйте, Камила! Меня зовут Алия, клиника SmileDent. Вы оставляли заявку на имплантацию?" },
      { speaker: "client", text: "Да, здравствуйте! Хочу узнать подробнее." },
      { speaker: "manager", text: "Подскажите, какой зуб вас беспокоит? Верхний или нижний?" },
      { speaker: "client", text: "Нижний, жевательный. Удалили полгода назад." },
      { speaker: "manager", text: "Для жевательных зубов мы рекомендуем Osstem — отличное соотношение цены и качества. Стоимость от 180 000 ₸, включая коронку." },
      { speaker: "client", text: "А есть рассрочка?" },
      { speaker: "manager", text: "Да, рассрочка до 12 месяцев без процентов! Давайте запишу вас на бесплатную консультацию к хирургу?" },
      { speaker: "client", text: "Давайте, на четверг!" },
    ],
  },
  {
    id: "5",
    manager_name: "AI-Агент (WhatsApp)",
    interaction_type: "whatsapp",
    duration_seconds: 0,
    ai_score: 98,
    ai_summary: "AI-агент безупречно провёл диалог, отработал возражение о безопасности и записал клиента. Не упомянул акцию дня.",
    checklist: [
      { name: "Приветствие", passed: true, comment: "" },
      { name: "Выявление потребности", passed: true, comment: "" },
      { name: "Отработка возражений", passed: true, comment: "" },
      { name: "Закрытие на визит", passed: true, comment: "" },
    ],
    transcript: [
      { speaker: "client", text: "Здравствуйте! Сколько стоит отбеливание?" },
      { speaker: "manager", text: "Добрый день! 😊 Отбеливание Zoom 4 — 45 000 ₸. Результат до 8 тонов за 1 сеанс. Безопасно для эмали. Хотите записаться на бесплатную консультацию?" },
      { speaker: "client", text: "А это безопасно?" },
      { speaker: "manager", text: "Абсолютно! Zoom 4 одобрена мировыми стоматологическими ассоциациями. Эмаль не повреждается. Когда вам удобно прийти?" },
      { speaker: "client", text: "Давайте на субботу!" },
      { speaker: "manager", text: "Записала вас на субботу 10:00! Адрес: ул. Абая 150, 2 этаж. Напомню за день до визита 😊" },
    ],
  },
  {
    id: "6",
    manager_name: "Менеджер Дамир",
    interaction_type: "whatsapp",
    duration_seconds: 0,
    ai_score: 25,
    ai_summary: "Менеджер отвечал односложно, не проявил заинтересованности. Ответил 'ну как хотите'. Потерян лид с потенциалом 960 000 ₸.",
    checklist: [
      { name: "Приветствие", passed: false, comment: "Не поздоровался по имени" },
      { name: "Выявление потребности", passed: false, comment: "Не задал ни одного вопроса" },
      { name: "Отработка возражений", passed: false, comment: "Ответил 'ну как хотите'" },
      { name: "Закрытие на визит", passed: false, comment: "Не предложил записаться" },
    ],
    transcript: [
      { speaker: "client", text: "Добрый день, сколько стоят виниры?" },
      { speaker: "manager", text: "от 120к", is_mistake: true, ai_comment: "Ответ через 5 минут, без приветствия, без форматирования. Нарушен стандарт скорости ответа (макс 2 мин)." },
      { speaker: "client", text: "А подешевле есть?" },
      { speaker: "manager", text: "нет", is_mistake: true, ai_comment: "Односложный ответ. Не предложил композитные виниры (от 40к) или рассрочку." },
      { speaker: "client", text: "Ясно, спасибо" },
      { speaker: "manager", text: "👍", is_mistake: true, ai_comment: "Не попытался удержать клиента. Потерян лид с потенциалом 960 000 ₸ (8 виниров × 120 000 ₸)." },
    ],
  },
  {
    id: "7",
    manager_name: "Менеджер Алия",
    interaction_type: "call",
    duration_seconds: 320,
    ai_score: 85,
    ai_summary: "Хороший звонок. Менеджер хорошо отработала диалог, но забыла предложить рассрочку при обсуждении цены.",
    checklist: [
      { name: "Приветствие", passed: true, comment: "" },
      { name: "Выявление потребности", passed: true, comment: "" },
      { name: "Отработка возражений", passed: true, comment: "Не упомянула рассрочку" },
      { name: "Закрытие на визит", passed: true, comment: "" },
    ],
    transcript: [
      { speaker: "manager", text: "Здравствуйте, Сергей! Клиника SmileDent, Алия. Вы интересовались установкой брекетов?" },
      { speaker: "client", text: "Да, для дочери 14 лет." },
      { speaker: "manager", text: "Подскажите, вы уже консультировались с ортодонтом?" },
      { speaker: "client", text: "Нет ещё, хотели узнать цены сначала." },
      { speaker: "manager", text: "У нас металлические от 350 000, керамические от 450 000. Запишу на бесплатную консультацию?" },
      { speaker: "client", text: "Давайте на следующую неделю." },
    ],
  },
];
